version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181"
    networks:
      - my-networks

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    links:
      - "zookeeper"
    restart: on-failure
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - my-networks

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=plabs
      - POSTGRES_PASSWORD=plabs
      - POSTGRES_DB=shoping
    ports:
      - "5432:5432"
    restart: always
    networks:
      - my-networks

  my-app:
    build:
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - kafka
      - postgres
      - migrate
    ports:
      - "8000:8000"
    networks:
      - my-networks
    links:
      - "postgres"

  migrate:
    image: migrate/migrate

    depends_on:
      - postgres
    command:
      [
        "migrate",
        "-path",
        "database/migrations",
        "-database",
        "postgres://plabs:plabs@postgres:5432/shoping?sslmode=disable",
        "--verbose",
        "up",
      ]
    networks:
      - my-networks

networks:
  my-networks:
    driver: bridge
