CREATE TABLE IF NOT EXISTS "sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "guid" varchar UNIQUE PRIMARY KEY NOT NULL,
  "user_guid" varchar NOT NULL,
  "client_ip" varchar NOT NULL,
  "refresh_token" varchar NOT NULL,
  "user_agent" varchar NOT NULL,
  "expired_at" timestamp,
  "created_at" timestamp NOT NULL DEFAULT (now())
);
